version: 2
updates:
  - package-ecosystem: nuget
    directory: /src
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /src/Anichron.API
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: docker
    directory: /src/Anichron.Worker
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
