// <auto-generated />
using System;
using Anichron.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anichron.Core.Migrations
{
    [DbContext(typeof(AnichronDbContext))]
    [Migration("20260927145042_AddSchemaComments")]
    partial class AddSchemaComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anichron.Core.Domain.AssetInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("LastViewed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId", "AssetId")
                        .IsUnique();

                    b.ToTable("Interactions", t =>
                        {
                            t.HasComment("Per-user state for one asset. Never shared between users: two people looking at the same file each get their own row. Drives flashback weighting — hidden excludes, starred always includes and sorts first, liked raises DisplayWeight.");
                        });
                });

            modelBuilder.Entity("Anichron.Core.Domain.Burst", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrimaryAssetId")
                        .HasColumnType("uuid")
                        .HasComment("The frame chosen to represent the burst. Restrict on delete: losing the cover would leave a group that cannot be rendered.");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryAssetId");

                    b.ToTable("Bursts", t =>
                        {
                            t.HasComment("Groups a rapid-fire sequence so a flashback shows one memory rather than nine near-identical frames. The table and schema exist; burst DETECTION is not yet implemented in the Worker, so in a running system this table is empty.");
                        });
                });

            modelBuilder.Entity("Anichron.Core.Domain.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasComment("Hash, never the token itself. 44 chars — base64 of a 32-byte value.");

                    b.Property<Instant?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsedByUserId");

                    b.ToTable("Invites", t =>
                        {
                            t.HasComment("Admin-issued registration tokens. Registration requires one; the first user (bootstrap admin) is exempt. Redemption is a read-then-write race, which is why this is the only table carrying a concurrency token.");
                        });
                });

            modelBuilder.Entity("Anichron.Core.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BurstId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("XXHash64 of the file contents. Dedup is deliberately CONFIG-SCOPED: the same bytes under two storage configs are two assets, which is what makes multi-user work. A global unique index on this column alone would break that and must never be added.");

                    b.Property<LocalDateTime>("DateCaptured")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasComment("See Month — the pair backs IX_MediaAsset_Flashback.");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Path relative to the storage config root. Not to be confused with ProxyFiles.ProxyPath, which is relative to the proxy root.");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("boolean")
                        .HasComment("Set by reconciliation when a file is gone from the NAS. Soft rather than hard so the user's interactions survive a temporarily unmounted share.");

                    b.Property<Instant>("LastSeenOnNas")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasComment("Stored apart from DateCaptured so \"On This Day\" is an index lookup on (Month, Day) rather than an EXTRACT() scan over every row.");

                    b.Property<Guid?>("PairedAssetId")
                        .HasColumnType("uuid")
                        .HasComment("Live Photo pairing: the HEIC parent points at its MOV child. SetNull on delete so losing one half leaves the other a usable standalone asset.");

                    b.Property<Guid>("StorageConfigId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BurstId");

                    b.HasIndex("IsSoftDeleted")
                        .HasDatabaseName("IX_MediaAssets_Active")
                        .HasFilter("\"IsSoftDeleted\" = false");

                    b.HasIndex("PairedAssetId");

                    b.HasIndex("Month", "Day")
                        .HasDatabaseName("IX_MediaAsset_Flashback");

                    b.HasIndex("StorageConfigId", "ContentHash");

                    b.HasIndex("StorageConfigId", "FilePath")
                        .IsUnique();

                    b.ToTable("MediaAssets", t =>
                        {
                            t.HasComment("One row per media file, scoped to a storage config. Written ONLY by the Worker — the API never writes media data.");
                        });
                });

            modelBuilder.Entity("Anichron.Core.Domain.Metadata", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("CameraMake")
                        .HasColumnType("text");

                    b.Property<string>("CameraModel")
                        .HasColumnType("text");

                    b.Property<int?>("DurationInSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LensModel")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("OrientationDegrees")
                        .HasColumnType("integer")
                        .HasComment("Rotation needed to display the image upright, already normalised from the raw EXIF orientation flag so consumers never interpret the flag themselves.");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("AssetId");

                    b.ToTable("Metadata", t =>
                        {
                            t.HasComment("EXIF data, 1:1 with MediaAsset and keyed by it — there is no separate Id. Populated by ExifExtractionMiddleware; every field is best-effort, because a file may carry no EXIF at all.");
                        });
                });

            modelBuilder.Entity("Anichron.Core.Domain.ProxyFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProxyPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Path relative to the proxy root, sharded by CONTENT rather than by ingestion attempt so a retry overwrites its own debris instead of stranding it. IProxyDirectoryStrategy is the single place that rule lives.");

                    b.Property<string>("ProxyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Thumbnail, WebVideo, FullPreview or BlurHash, persisted as text. Note BlurHash is an ordinary proxy ROW whose content is a file — not a string column on the asset.");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("ProxyFiles", t =>
                        {
                            t.HasComment("One row per generated artefact on the local SSD. An asset has several. Written only by ProxyStagingWriter, at the moment the file reaches its final name.");
                        });
                });

            modelBuilder.Entity("Anichron.Core.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Hash, never the token itself — a database disclosure must not hand out usable sessions.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshTokens", t =>
                        {
                            t.HasComment("Issued and revoked by the API; expired rows are swept by the Worker's TokenCleanupService. One of the few tables both services touch.");
                        });
                });

            modelBuilder.Entity("Anichron.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasComment("Set by an admin reset. MustChangePasswordMiddleware then 403s every route except the handful needed to change it.");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Argon2id. The parameters live with the hasher, not here, so rotating them does not require a migration.");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("Users", t =>
                        {
                            t.HasComment("Owns storage configs and interactions. All identity writes happen in the API; the Worker only reads.");
                        });
                });

            modelBuilder.Entity("Anichron.Core.Domain.UserStorageConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("GLOBALLY unique, not per user: a path cannot be assigned to two configs across all users. Two users indexing the same directory would duplicate every asset and let one user's config removal cascade away the other's rows.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("StorageConfigs", t =>
                        {
                            t.HasComment("A NAS root assigned to one user. This is the boundary that scopes assets to a user and lets several Workers each monitor a separate config.");
                        });
                });

            modelBuilder.Entity("Anichron.Core.Domain.AssetInteraction", b =>
                {
                    b.HasOne("Anichron.Core.Domain.MediaAsset", "Asset")
                        .WithMany("Interactions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anichron.Core.Domain.User", "User")
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anichron.Core.Domain.Burst", b =>
                {
                    b.HasOne("Anichron.Core.Domain.MediaAsset", "PrimaryAsset")
                        .WithMany()
                        .HasForeignKey("PrimaryAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimaryAsset");
                });

            modelBuilder.Entity("Anichron.Core.Domain.Invite", b =>
                {
                    b.HasOne("Anichron.Core.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anichron.Core.Domain.User", "UsedBy")
                        .WithMany()
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("UsedBy");
                });

            modelBuilder.Entity("Anichron.Core.Domain.MediaAsset", b =>
                {
                    b.HasOne("Anichron.Core.Domain.Burst", "Burst")
                        .WithMany("Assets")
                        .HasForeignKey("BurstId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anichron.Core.Domain.MediaAsset", "PairedAsset")
                        .WithMany()
                        .HasForeignKey("PairedAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anichron.Core.Domain.UserStorageConfig", "StorageConfig")
                        .WithMany("Assets")
                        .HasForeignKey("StorageConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Burst");

                    b.Navigation("PairedAsset");

                    b.Navigation("StorageConfig");
                });

            modelBuilder.Entity("Anichron.Core.Domain.Metadata", b =>
                {
                    b.HasOne("Anichron.Core.Domain.MediaAsset", "Asset")
                        .WithOne("Metadata")
                        .HasForeignKey("Anichron.Core.Domain.Metadata", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Anichron.Core.Domain.ProxyFile", b =>
                {
                    b.HasOne("Anichron.Core.Domain.MediaAsset", "Asset")
                        .WithMany("ProxyFiles")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Anichron.Core.Domain.RefreshToken", b =>
                {
                    b.HasOne("Anichron.Core.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anichron.Core.Domain.UserStorageConfig", b =>
                {
                    b.HasOne("Anichron.Core.Domain.User", "User")
                        .WithMany("StorageConfigs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anichron.Core.Domain.Burst", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Anichron.Core.Domain.MediaAsset", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("Metadata");

                    b.Navigation("ProxyFiles");
                });

            modelBuilder.Entity("Anichron.Core.Domain.User", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StorageConfigs");
                });

            modelBuilder.Entity("Anichron.Core.Domain.UserStorageConfig", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
