// <auto-generated />
using System;
using Anichron.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anichron.Core.Migrations
{
    [DbContext(typeof(AnichronDbContext))]
    [Migration("20260507074514_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anichron.Core.Domain.AssetInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("LastViewed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId", "AssetId")
                        .IsUnique();

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("Anichron.Core.Domain.Burst", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrimaryAssetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryAssetId");

                    b.ToTable("Bursts");
                });

            modelBuilder.Entity("Anichron.Core.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BurstId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<LocalDateTime>("DateCaptured")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("boolean");

                    b.Property<Instant>("LastSeenOnNas")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LivePhotoPairId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<Guid>("StorageConfigId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BurstId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("IsSoftDeleted")
                        .HasDatabaseName("IX_MediaAssets_Active")
                        .HasFilter("\"IsSoftDeleted\" = false");

                    b.HasIndex("LivePhotoPairId");

                    b.HasIndex("Month", "Day")
                        .HasDatabaseName("IX_MediaAsset_Flashback");

                    b.HasIndex("StorageConfigId", "FilePath")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("Anichron.Core.Domain.Metadata", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("CameraMake")
                        .HasColumnType("text");

                    b.Property<string>("CameraModel")
                        .HasColumnType("text");

                    b.Property<float?>("DurationSeconds")
                        .HasColumnType("real");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real");

                    b.Property<string>("LensModel")
                        .HasColumnType("text");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real");

                    b.Property<int>("OrientationDegrees")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("AssetId");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Anichron.Core.Domain.ProxyFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProxyPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProxyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("ProxyFiles");
                });

            modelBuilder.Entity("Anichron.Core.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Anichron.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Anichron.Core.Domain.UserStorageConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("StorageConfigs");
                });

            modelBuilder.Entity("Anichron.Core.Domain.AssetInteraction", b =>
                {
                    b.HasOne("Anichron.Core.Domain.MediaAsset", "Asset")
                        .WithMany("Interactions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anichron.Core.Domain.User", "User")
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anichron.Core.Domain.Burst", b =>
                {
                    b.HasOne("Anichron.Core.Domain.MediaAsset", "PrimaryAsset")
                        .WithMany()
                        .HasForeignKey("PrimaryAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimaryAsset");
                });

            modelBuilder.Entity("Anichron.Core.Domain.MediaAsset", b =>
                {
                    b.HasOne("Anichron.Core.Domain.Burst", "Burst")
                        .WithMany("Assets")
                        .HasForeignKey("BurstId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anichron.Core.Domain.MediaAsset", "LivePhotoPair")
                        .WithMany()
                        .HasForeignKey("LivePhotoPairId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anichron.Core.Domain.UserStorageConfig", "StorageConfig")
                        .WithMany("Assets")
                        .HasForeignKey("StorageConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Burst");

                    b.Navigation("LivePhotoPair");

                    b.Navigation("StorageConfig");
                });

            modelBuilder.Entity("Anichron.Core.Domain.Metadata", b =>
                {
                    b.HasOne("Anichron.Core.Domain.MediaAsset", "Asset")
                        .WithOne("Metadata")
                        .HasForeignKey("Anichron.Core.Domain.Metadata", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Anichron.Core.Domain.ProxyFile", b =>
                {
                    b.HasOne("Anichron.Core.Domain.MediaAsset", "Asset")
                        .WithMany("ProxyFiles")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Anichron.Core.Domain.RefreshToken", b =>
                {
                    b.HasOne("Anichron.Core.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anichron.Core.Domain.UserStorageConfig", b =>
                {
                    b.HasOne("Anichron.Core.Domain.User", "User")
                        .WithMany("StorageConfigs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anichron.Core.Domain.Burst", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Anichron.Core.Domain.MediaAsset", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("Metadata");

                    b.Navigation("ProxyFiles");
                });

            modelBuilder.Entity("Anichron.Core.Domain.User", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StorageConfigs");
                });

            modelBuilder.Entity("Anichron.Core.Domain.UserStorageConfig", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
